# Changes the server command to use nodemon instead for development.
---

services:
  server:
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - ./source:/usr/src/app/source:ro
    command: npm run dev
  
  database:
    ports:
      - 5432:5432

  cache:
    ports:
      - 6379:6379
      - 8001:8001