FROM redis/redis-stack:7.4.0-v0
WORKDIR /

# Forcing the use of a custom redis configuration
COPY ./redis.config /redis-stack.conf 

LABEL org.opencontainers.image.created="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"