# Changes the server command to use nodemon instead for development.
---

services:
  server:
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app/
      - ~/.bashrc:/root/.bashrc:ro
    command: npm run dev
  
  database:
    ports:
      - 6379:6379
      - 8001:8001