FROM node:21
WORKDIR /usr/src/app

# Install dependencies before copying the rest of the application code.
COPY ../package*.json ./
RUN npm install

# Copy the rest of the application code.
COPY .. .

# installing the network tools for debugging
RUN apt-get update && apt-get install -y net-tools lsof

# opening the port
EXPOSE 80

# starting the app
CMD ["sh", "-c", "echo 'Path: $(env | grep PWD) has files:' && ls -All -h && node ./source/app.js"]
# CMD ["node", "index.js"] 