# The development stack of this application
---

services:

  server:
    image: sth123/pdf-automator
    container_name: pdf-automator-server
    hostname: pdf-automator-server
    restart: unless-stopped
    ports:
      - 3001:80
    networks:
      - default
    env_file:
      - ../.env
    volumes:
      - ${APPDATA}/server/data/:/usr/src/app/data
    depends_on:
      - database
      - cache
    working_dir: /usr/src/app
    tty: true

  database:
    image: postgres:latest
    container_name: pdf-automator-database
    hostname: pdf-automator-database
    restart: unless-stopped
    networks:
      - default
    env_file:
      - ../.env
    volumes:
      - ${APPDATA}/postgres/data:/var/lib/postgresql/data
    tty: true

  cache:
    image: redis:latest
    container_name: pdf-automator-cache
    hostname: pdf-automator-cache
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ${APPDATA}/cache/d–∞ta:/root/redis
      - ${APPDATA}/cache/config:/usr/local/etc/redis/
    tty: true

networks:
  default:
    name: pdf-automator